use_frameworks!
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ZQComponents_Example' do
  pod 'ZQComponents', :path => '../'
  
#  pod 'YogaKit'
  pod 'YogaKit', '~> 1.7'
#  pod 'WeexSDK'
  pod 'ReactiveObjC'

  target 'ZQComponents_Tests' do
    inherit! :search_paths

    
  end
end
